export default {
  // Palette / tools
  'Search in diagram': '查找',
  'Activate hand tool': '激活抓手工具',
  'Activate lasso tool': '激活套索工具',
  'Activate create/remove space tool': '激活创建/删除间距工具',
  'Activate global connect tool': '激活全局连线工具',
  'Create start event': '创建开始事件',
  'Create intermediate/boundary event': '创建中间/边界事件',
  'Create end event': '创建结束事件',
  'Create gateway': '创建网关',
  'Create task': '创建任务',
  'Create data object reference': '创建数据对象引用',
  'Create data store reference': '创建数据存储引用',
  'Create expanded sub-process': '创建展开子流程',
  'Create pool/participant': '创建池/参与者',
  'Create group': '创建分组',

  // Context pad
  'Append compensation activity': '追加补偿活动',
  'Append conditional intermediate catch event': '追加条件中间捕获事件',
  'Append end event': '追加结束事件',
  'Append gateway': '追加网关',
  'Append intermediate/boundary event': '追加中间/边界事件',
  'Append message intermediate catch event': '追加消息中间捕获事件',
  'Append receive task': '追加接收任务',
  'Append signal intermediate catch event': '追加信号中间捕获事件',
  'Append task': '追加任务',
  'Append timer intermediate catch event': '追加定时中间捕获事件',
  'Add lane above': '在上方添加泳道',
  'Divide into two lanes': '拆分为两条泳道',
  'Divide into three lanes': '拆分为三条泳道',
  'Add lane below': '在下方添加泳道',
  'Add text annotation': '添加文本注释',
  'Change element': '更改元素',
  'Connect to other element': '连接到其他元素',
  'Connect using association': '使用关联连接',
  'Connect using Association': '使用关联连接',
  'Connect using data input association': '使用数据输入关联连接',
  'Delete': '删除',
  'Remove': '移除',
  'Cancel': '取消',

  // Generic BPMN labels
  'Start event': '开始事件',
  'Intermediate throw event': '中间抛出事件',
  'End event': '结束事件',
  'Message start event': '消息开始事件',
  'Timer start event': '定时开始事件',
  'Conditional start event': '条件开始事件',
  'Signal start event': '信号开始事件',
  'Message intermediate catch event': '消息中间捕获事件',
  'Message intermediate throw event': '消息中间抛出事件',
  'Timer intermediate catch event': '定时中间捕获事件',
  'Escalation intermediate throw event': '升级中间抛出事件',
  'Conditional intermediate catch event': '条件中间捕获事件',
  'Link intermediate catch event': '链接中间捕获事件',
  'Link intermediate throw event': '链接中间抛出事件',
  'Compensation intermediate throw event': '补偿中间抛出事件',
  'Signal intermediate catch event': '信号中间捕获事件',
  'Signal intermediate throw event': '信号中间抛出事件',
  'Message end event': '消息结束事件',
  'Escalation end event': '升级结束事件',
  'Error end event': '错误结束事件',
  'Compensation end event': '补偿结束事件',
  'Signal end event': '信号结束事件',
  'Terminate end event': '终止结束事件',
  'Parallel gateway': '并行网关',
  'Inclusive gateway': '包容网关',
  'Complex gateway': '复杂网关',
  'Event-based gateway': '事件网关',
  'Exclusive gateway': '排他网关',
  'User task': '用户任务',
  'Service task': '服务任务',
  'Send task': '发送任务',
  'Receive task': '接收任务',
  'Manual task': '手工任务',
  'Business rule task': '业务规则任务',
  'Script task': '脚本任务',
  'Call activity': '调用活动',
  'Sub-process (collapsed)': '子流程（折叠）',
  'Sub-process (expanded)': '子流程（展开）',
  'Parallel multi-instance': '并行多实例',
  'Sequential multi-instance': '串行多实例',
  'Event sub-process': '事件子流程',
  'Data store reference': '数据存储引用',
  'Data object reference': '数据对象引用',
  'Participant multiplicity': '参与者多重性',
  'Empty pool/participant (removes content)': '空池/参与者（移除内容）',
  'Create {type}': '创建 {type}',
  'Append {type}': '追加 {type}',
  'Must provide a value': '必须提供一个值',

  // Properties panel
  Task: '任务',
  ID: '编号',
  Name: '名称',
  General: '常规',
  Message: '消息',
  Documentation: '文档',
  Process: '流程',
  Compensation: '补偿',
  'Element documentation': '元素文档',
  Listeners: '监听器',
  Listener: '监听器',
  Expression: '表达式',
  '表达式': '表达式',
  Timer: '定时器',
  Signal: '信号',
  Escalation: '升级',
  Error: '错误',
  'Link name': '链接名称',
  Link: '链接',
  Executable: '可执行',
  Event: '事件',
  Type: '类型',
  Value: '值',
  Label: '标签',
  Properties: '属性',
  Form: '表单',
  Forms: '表单',
  Details: '详情',
  Condition: '条件',
  Script: '脚本',
  Resource: '资源',
  Version: '版本',
  Category: '分类',
  ConditionExpression: '条件表达式',
  'Multi-instance': '多实例',
  'Default flow': '默认流',
  'Sequence flow': '顺序流',
  User: '用户',
  'Please select user': '请选择用户',
  Parameter: '参数名',
  Parameters: '参数',
  Extensions: '扩展属性',
  Key: '属性',
  Create: '创建',
  'Delete item': '删除项',
  'Create new list item': '创建新项',
  'Toggle section': '切换展开/收起',
  'Toggle list item': '切换展开/收起',
  'Section contains data': '当前分组已配置数据',
  'Section contains an error': '当前分组存在错误',
  'List contains {numOfItems} item': '列表包含 {numOfItems} 项',
  'List contains {numOfItems} items': '列表包含 {numOfItems} 项',
  'List contains {numofitems} item': '列表包含 {numofitems} 项',
  'List contains {numofitems} items': '列表包含 {numofitems} 项',
  '<empty>': '未定义',
  'Element Variable': '元素变量',
  'Element variable': '元素变量',
  'Form key': '表单 Key',
  Collection: '集合',
  'Completion condition': '完成条件',
  'Completion Condition': '完成条件',
  'Loop cardinality': '循环次数',
  'Loop Cardinality': '循环次数',
  Exclusive: '排他',
  Candidate: '候选',
  'Candidate Users': '候选用户',
  'Candidate Groups': '候选组',
  Assignee: '办理人',
  'Due Date': '到期时间',
  'Follow Up Date': '跟进日期',
  Priority: '优先级',
  Variables: '变量',
  'Task Listener': '任务监听器',
  'Execution Listener': '执行监听器',
  'Field Injections': '字段注入',
  Fields: '字段',
  'Input Parameters': '输入参数',
  'Output Parameters': '输出参数',
  'Input Parameter': '输入参数',
  'Output Parameter': '输出参数',
  'Input/Output': '输入/输出',
  'Form Key': '表单 Key',
  'Business Key': '业务 Key',
  'Job Configuration': '任务配置',
  'Retry Time Cycle': '重试时间周期',
  'Job Priority': '任务优先级',
  'History Time To Live': '历史保留时长',
  Startable: '可启动',
  'Connector Id': '连接器 ID',
  Connector: '连接器',
  'Configure Connector': '配置连接器',
  'Must configure Connector': '必须配置连接器',
  Implementation: '实现方式',
  'Result Variable': '结果变量',
  Topic: '主题',
  External: '外部',
  'Variable Name': '变量名',
  'Variable Event': '变量事件',
  'Wait for Completion': '等待完成',
  'Activity Ref': '活动引用',
  'Version Tag': '版本标签',
  ConditionType: '条件类型',
  'Condition Type': '条件类型',
  'Called Element': '调用元素',
  'CallActivity Type': '调用活动类型',
  'Candidate Starter Configuration': '候选启动人配置',
  'Candidate Starter Groups': '候选启动组',
  'Candidate Starter Users': '候选启动用户',
  'Tasklist Configuration': '任务列表配置',
  'Task Priority': '任务优先级',
  'Specify more than one group as a comma separated list.': '多个组请使用逗号分隔',
  'Specify more than one user as a comma separated list.': '多个用户请使用逗号分隔',
  'Specify more than one variable change event as a comma separated list.': '多个变量事件请使用逗号分隔',
  'This maps to the process definition key.': '该值会映射到流程定义 Key',
  'The follow up date as an EL expression (e.g. ${someDate} or an ISO date (e.g. 2015-06-26T09:54:00)': '跟进日期需为 EL 表达式或 ISO 日期',
  'The due date as an EL expression (e.g. ${someDate} or an ISO date (e.g. 2015-06-26T09:54:00)': '到期时间需为 EL 表达式或 ISO 日期',
  'Create UserTask': '创建用户任务',
  'Create CallActivity': '创建调用活动',
  'Add Constraint': '添加约束',
  Config: '配置',
  Add: '添加',
  Values: '值列表',
  'Add Value': '添加值',
  Validation: '校验',
  'Default Value': '默认值',
  'Form Field': '表单字段',
  'Form Fields': '表单字段',
  'Add Property': '添加属性',
  Property: '属性',
  'Field Injection': '字段注入',
  'Delegate Expression': '代理表达式',
  'Java Class': 'Java 类',
  'Event Type': '事件类型',
  'Listener Type': '监听器类型',
  'Script Format': '脚本格式',
  'Script Type': '脚本类型',
  'Inline Script': '内联脚本',
  'External Script': '外部脚本',
  Date: '日期',
  Duration: '持续时间',
  Cycle: '循环',
  'Signal Name': '信号名称',
  'Message Name': '消息名称',
  Initiator: '发起人',
  'Asynchronous Continuations': '异步延续',
  'Asynchronous Before': '前置异步',
  'Asynchronous After': '后置异步',
  'Message Boundary Event': '消息边界事件',
  'Message Boundary Event (non-interrupting)': '消息边界事件（非中断）',
  'Timer Boundary Event': '定时边界事件',
  'Timer Boundary Event (non-interrupting)': '定时边界事件（非中断）',
  'Escalation Boundary Event': '升级边界事件',
  'Escalation Boundary Event (non-interrupting)': '升级边界事件（非中断）',
  'Conditional Boundary Event': '条件边界事件',
  'Conditional Boundary Event (non-interrupting)': '条件边界事件（非中断）',
  'Error Boundary Event': '错误边界事件',
  'Cancel Boundary Event': '取消边界事件',
  'Signal Boundary Event': '信号边界事件',
  'Signal Boundary Event (non-interrupting)': '信号边界事件（非中断）',
  'Compensation Boundary Event': '补偿边界事件',
  Transaction: '事务',
  'Sub Process': '子流程',
  'Collapsed Pool': '折叠池',
  'Expanded Pool': '展开池',
  'Configure element': '配置元素',
  'Open minimap': '打开小地图',
  'Close minimap': '关闭小地图',
  'no parent for {element} in {parent}': '{parent} 中不存在 {element} 的父元素',
  'no shape type specified': '未指定图形类型',
  'flow elements must be children of pools/participants': '流程元素必须位于池/参与者内部',
  'more than {count} child lanes': '子泳道数量超过 {count}',
  'element required': '元素不能为空',
  'diagram not part of bpmn:Definitions': '流程图不属于 bpmn:Definitions',
  'no diagram to display': '没有可显示的流程图',
  'no process or collaboration to display': '没有可显示的流程或协作',
  'already rendered {element}': '{element} 已经渲染过',
  'failed to import {element}': '导入 {element} 失败',

  // Custom texts used by this project
  'Task list': '任务列表',
  'Audit node': '审核节点',
  'Edit expression': '编辑表达式',
  'Assignment event': '任务分派事件',
  'All events': '所有事件'
};
